### ISSUE TITLE
`Hashed` shouldn't provide `AsMut`

### ISSUE THREAD

**Issue by Lucretiel** [facebookincubator/gazebo#14]
Currently, `Hashed` provides `AsMut`, which allows mutable access to the wrapped value. This means that the value can change, without the pre-computed hash also being changed. Either `AsMut` should be removed, or `self.hash` should be replaced with `Option<u64>` (or `Option<NonZeroU64>`, and the internal logic updated so that mutable access clears the hash so it can be recomputed next time `hash` is called.

**Comment by ndmitchell** [comment]
You're completely right - I'll put up a patch to remove the AsMut. Making it an Option would be possible, but given we hash on construction, it feels like a weird corner case to occasionally lose the hash.

**Comment by ndmitchell** [comment]
Done in 6327eea9d087f375c71832c30fdfc9902a4e4b3a
