### ISSUE TITLE
The install instructions aren't applicable

### ISSUE THREAD

**Issue by cuviper** [facebookincubator/gazebo#2]
The README says:
> Gazebo can be installed with the standard `cargo install` pattern.

But that's only for binaries, and `gazebo` is a library. Shouldn't this instead talk about adding it as a dependency to `Cargo.toml`?

**Comment by ndmitchell** [comment]
Thanks for bringing this up - agreed it's not quite accurate. I was going for the idea that you use the standard Cargo patterns (e.g. add to Cargo.toml, run cargo install). Although given the ubiquity of those patterns in the Rust ecosystem, and given that Gazebo is 100% normal, perhaps we just need to say nothing? Taking a look at a few representative Rust libraries, a lot of them just omit this. Or if you think some specific information would be useful, what do you think that would be? Or is there a good link to point people at how to make use of a library?

**Comment by cuviper** [comment]
Maybe you could just say that it's a standard crates.io dependency, and link here:
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

**Comment by ndmitchell** [comment]
Great idea - fixed in b7ae9563c05f7cd667359036cae2b772ef4cc564.
