### ISSUE TITLE
SIGSEGV when running tests with -Zrandomize-layout due to repr(Rust) transmute

### ISSUE THREAD

**Issue by saethlin** [facebookincubator/gazebo#6]
I can product a SIGSEGV from this crate's test suite (version 0.7.1) by running
```
RUSTFLAGS="-Zrandomize-layout -Zlayout-seed=1" cargo +nightly test -- --test-threads=1
```
The `--test-threads=1` just helps see which test is failing.

The segfault occurs due to this transmute:
https://github.com/facebookincubator/gazebo/blob/d85b41e081a5f94d25da723630b0b223f9997e2b/gazebo/src/cell.rs#L65
This is an attempt to transmute between two `repr(Rust)` types, one of which is in the standard library. This transmute is not necessarily UB, but `repr(Rust)` types do not have a guaranteed layout, so the current behavior of `-Zrandomize-layout` can swap the field order inside this crates's `ARef` struct, causing the fields of `ARef` and `Ref` to no longer line up as appears intended.

FYI this is not fixable by making `ARef` a `repr(C)` struct, because the layout of `std::cell::Ref` is unstable too because it is `repr(Rust)`. This instability can be observed by adding a `-Zbuild-std` to the cargo invocation.

----

```
rustc 1.63.0-nightly (ec55c6130 2022-06-10)
binary: rustc
commit-hash: ec55c61305eaf385fc1b93ac9a78284b4d887fe5
commit-date: 2022-06-10
host: x86_64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.5
```

**Comment by ndmitchell** [comment]
This was introduced in fc2f7604af6472912842f6a245e37a1772750d78, with the comment:

> Requires making assumptions about the value of Ref (ick, but we do add lots of tests for them) and gives us a perf win.

@stepancheg - a lot of the ARef was in rust-starlark - do you think we are now less sensitive to that?

@saethlin Is the `-Zrandomize-layout` something you are doing to experiment, or is it actually an issue you are hitting for real?

**Comment by stepancheg** [comment]
@ndmitchell reverting to previous implementation may be noticable.

But we can simply reimplement `RefCell`, so we won't rely on it's layout in the standard library.

**Comment by saethlin** [comment]
> Is the `-Zrandomize-layout` something you are doing to experiment, or is it actually an issue you are hitting for real?

I'm using the flag to find codebases that rely on the exact layout algorithm rustc currently uses for `repr(Rust)` types, which is what the flag is for. I don't really know what you mean by "for real".
